# Generated by Django 4.2.16 on 2024-12-02 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('P', 'Popular'), ('C', 'Confort'), ('L', 'Luxuoso'), ('E', 'Esportivo')], default='P', max_length=1)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locadora.carro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locadora.usuario')),
            ],
        ),
    ]
